import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const backupCss = await readFile(join(packageRoot, "src/features/skills/BackupView.css"), "utf8");
const backupView = await readFile(join(packageRoot, "src/features/skills/BackupView.tsx"), "utf8");
const accordionCss = await readFile(join(packageRoot, "src/components/shared/CollapsibleAccordion.css"), "utf8");

assert.doesNotMatch(backupCss, /\.backupContentItemRow(?:\s*>\s*div)?\s+span\s*\{/);
assert.match(backupCss, /\.backupDetailsDialog \{[\s\S]*height: min\(560px, calc\(100vh - 64px\)\);[\s\S]*display: flex;[\s\S]*flex-direction: column;/);
assert.match(backupCss, /\.backupDetailsBody \{[\s\S]*min-height: 0;[\s\S]*flex: 1 1 auto;[\s\S]*overflow-x: hidden;[\s\S]*overflow-y: auto;/);
assert.match(backupCss, /\.backupDetailsHomeBody \.settingsBackupVersionList \{[\s\S]*min-height: 0;[\s\S]*max-height: 280px;[\s\S]*flex: 0 1 auto;/);
assert.match(backupCss, /\.backupCategoryAccordion \{[\s\S]*flex: 0 0 auto;/);
assert.match(backupCss, /\.backupDetailsAccordionSection \[data-accordion-item="repository"\],[\s\S]*\.backupDetailsAccordionSection \[data-accordion-item="disconnect"\] \{[\s\S]*--collapsible-content-padding: 0 16px 16px;/);
assert.match(backupCss, /\.backupCategoryAccordion \{[\s\S]*--collapsible-surface: transparent;/);
assert.match(backupCss, /\.backupContentItemRow \{[\s\S]*min-height: var\(--data-table-table-row-height\);[\s\S]*gap: 12px;/);
assert.doesNotMatch(backupCss, /\.backupContentItemRow \{[^}]*border-top:/);
assert.match(backupView, /className="backupDetailsBody backupDetailsHomeBody"/);
assert.match(backupView, /className="backupDetailsSection backupDetailsAccordionSection"/);
assert.match(backupView, /import \{ CollapsibleAccordion,/);
assert.match(backupView, /function BackupCategoryAccordion\(/);
assert.match(backupView, /id: "repository",\s*title: "Repository",\s*content: <div className="settingsBackupFormGrid">/);
assert.match(backupView, /const mixed = selection\.enabled && itemCount > 0 && selectedCount > 0 && selectedCount < itemCount;/);
assert.match(backupView, /checked=\{checked\} mixed=\{mixed\}/);
assert.match(backupView, /title: "Sync contents"/);
assert.match(backupView, /`\$\{selectedCount\}\/\$\{itemCount\}`/);
assert.match(backupView, /title: "History"/);
assert.doesNotMatch(backupView, /activeCategory|contentCategory|setContentCategory|BackupDialogLeadingAction|backupDialogLeadingAction/);
assert.doesNotMatch(backupView, /Global managed skills|Global MCP configuration|Global rules|Global hooks/);
assert.doesNotMatch(backupView, /No global items/);
assert.match(backupView, /<strong className="dataCellTitle">\{item\.label\}<\/strong>/);
assert.match(backupView, /function backupCatalogSubtitle\(category: BackupCategory, item: BackupCatalogItem\)/);
assert.doesNotMatch(backupView, /Agent files|files: BackupCategorySelection/);
assert.doesNotMatch(backupView, /deviceLabel|Device label|setDeviceLabel/);
assert.match(backupView, /if \(category === "mcp"\) return ""/);
assert.match(backupView, /formatUserPath\(item\.detail\)/);
assert.match(backupView, /compactCommand\(item\.detail\)/);
assert.match(backupView, /subtitle \? <span className="dataCellSubLine">/);
assert.match(backupView, /const subtitle = backupCatalogSubtitle\(category\.key, item\)/);
